const SET_REGIONS: string = "SET_REGIONS";

const CHANGE_COUNTRY: string = "CHANGE_COUNTRY";

const GET_ALL_COUNTRIES: string = "GET_ALL_COUNTRIES";

const SET_QUERY: string = "SET_QUERY";
const RESET_QUERY: string = "RESET_QUERY";

const SET_COUNTRY: string = "SET_COUNTRY";

const RESET_COUNTRY: string = "RESET_COUNTRY";

const FETCH_SUCCESS: string = "FETCH_SUCCESS";

export {
  SET_REGIONS,
  CHANGE_COUNTRY,
  GET_ALL_COUNTRIES,
  SET_QUERY,
  RESET_QUERY,
  SET_COUNTRY,
  RESET_COUNTRY,
  FETCH_SUCCESS,
};
