const SET_REGIONS: string = "SET_REGIONS";

const CHANGE_COUNTRY: string = "CHANGE_COUNTRY";

const GET_ALL_COUNTRIES: string = "GET_ALL_COUNTRIES";

const SET_QUERY: string = "SET_QUERY";

export { SET_REGIONS, CHANGE_COUNTRY, GET_ALL_COUNTRIES, SET_QUERY };
